name: parkingzero
description: "ParkingZero - App de carteira, cashback e estacionamento."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management & DI
  flutter_bloc: ^9.0.0
  get_it: ^8.0.0

  # API & JSON
  dio: ^5.7.0
  json_annotation: ^4.9.0

  # Firebase & Auth
  firebase_core: ^3.10.0
  firebase_auth: ^5.5.0

  # Maps & Location
  google_maps_flutter: ^2.9.0
  location: ^6.0.0

  # UI & Design
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.0
  font_awesome_flutter: ^10.7.0
  sizer: ^3.0.1
  grpc: ^5.1.0
  protobuf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
