name: store_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  fixnum: ^1.1.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  grpc: ^5.1.0
  intl: ^0.20.2
  protobuf: ^6.0.0
  sizer: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
